# Generated by Django 4.2.1 on 2023-05-31 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('picture', models.ImageField(blank=True, default='/img/default_prod_img.png', upload_to='img', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('vendor', models.CharField(blank=True, default='', max_length=200, verbose_name='Производитель')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Рейтинг')),
                ('reviews_num', models.PositiveSmallIntegerField(default=0, verbose_name='Количество отзывов')),
                ('stock_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='base.category', verbose_name='Категория')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
