# Generated by Django 4.2.1 on 2023-05-31 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, default='', max_length=200, verbose_name='Способ оплаты')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Налог')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость доставки')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Итоговая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('paid_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время оплаты')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлен')),
                ('delivered_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
