# Generated by Django 4.2.1 on 2023-05-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Улица, дом, квартира')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость доставки')),
                ('order', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='base.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
            },
        ),
    ]
